[build]
  publish = "."

[[redirects]]
  from = "/videos"
  to = "/videos.html"
  status = 200

[[redirects]]
  from = "/apply"
  to = "/apply.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
